### PR TITLE
Add Nix-ified Maven Build

### PR DESCRIPTION
**Pull request by 404Wolf**
Add a minimal [Nix](http://nixos.org/) flake that provides a default package to build Missile wars. This allows for reproducible builds without the need to maintain multiple complex shell scripts (or provides an easy option to people who use `nix`).

### CODE REVIEW

**Comment by 404Wolf** [comment]
To do a nix build, install the [nix package manager](https://nixos.org/download/), and run `nix build` (you may need to add `--extra-experimental-features nix-command --extra-experimental-features flakes` if you haven't used nix and don't use flakes -- flakes are very common and there's a lot of drama over whether they really should be experimental)

**Comment by RedstoneFuture** [comment]
Thanks for the PR and for the explanation.

I will check to what extent NIX is currently known in Minecraft networks in practice. But if it is still too little known / rare, I would rather not include this support for now. Enabled support for something should also be tested, described and updated from time to time. I am not currently using it.

I will then report back here.

**Comment by 404Wolf** [comment]
Cool, sounds good! It's basically just an easy to use build script, but pure (locked to the correct maven deps and jdk version, etc), to use maven to get jars, not a new feature or adding anything to the plugin. I think it is much more reliable and easy to use than the current shell scripts.

**Comment by RedstoneFuture** [comment]
Hello,

I've been doing some research: NIX is actually becoming more and more popular. But not necessarily in the Minecraft plugin community, I think.

I don't use NIX personally, and I can't guarantee whether the NIX configuration will work correctly now or in a year's time. The build system doesn't necessarily belong as part of the repository. Perhaps you would like to outsource the build to a separate repository (“missilewars-NIX”)?

Thanks for the suggestion anyway!

**Pull request closed without merging**
